const en = {
  publicShareRateLimited: "Too many requests",
  publicShareRateLimitedHint: "Wait a moment and try opening this shared link again.",
  publicShareUnavailable: "This shared link is unavailable",
  publicShareUnavailableHint: "It may have been revoked, suspended, or the shared item is no longer available.",
  publicShareLoading: "Loading shared content…",
  publicSharePublicLink: "Public link",
  publicShareEmptyPlaylist: "No available videos",
  publicShareEmptyPlaylistHint: "This playlist currently contains no videos that can be shown publicly.",
  publicSharePlaylist: "Shared playlist",
  publicShareLoadMore: "Load more",
  publicShareNotFound: "Shared link not found",
  profilePermissionPublicSharing: "Public sharing",
  profilePermissionPublicSharingHint: "Create and manage public links to owned videos and playlists.",
  publicShareAction: "Public link",
  publicShareCreate: "Create public link",
  publicShareDisabledByAdmin: "Public sharing is disabled by an administrator.",
  publicShareCopy: "Copy public link",
  publicShareCopied: "Public link copied",
  publicShareLocalMedia: "Allow local media",
  publicShareLocalMediaHint: "Allows local media playback. Enabling this rotates the link.",
  publicShareRotate: "Rotate link",
  publicShareRotateConfirm: "Rotate this link? The previous URL will stop working immediately.",
  publicShareRevoke: "Revoke link",
  publicShareRevokeConfirm: "Revoke this public link? This cannot be undone.",
  publicShareActive: "Active",
  publicShareSuspended: "Suspended",
  publicShareTokenRotated: "The public link was rotated",
  publicShareError: "The public link could not be updated.",
  publicSharingSettingsNav: "Sharing",
  publicSharingTitle: "Public sharing",
  publicSharingDescription: "Manage read-only public links without exposing profiles or the rest of the application.",
  publicSharingMaster: "Enable public sharing",
  publicSharingMasterHint: "Controls every public link on this installation. Existing links remain stored while disabled.",
  publicSharingLinks: "Public links",
  publicSharingLinksHint: "Local media is off by default and can be enabled per link.",
  publicSharingEmpty: "No public links",
  publicSharingEmptyHint: "Create a link from a video or playlist page.",
  publicShareOwner: "Owner: {name}",
  publicShareVideo: "Video",
  publicShareUserPlaylist: "Personal playlist",
  publicShareFollowedPlaylist: "Followed playlist",
  publicSharePolicyDisabled: "Sharing is globally disabled",
  publicSharePermissionSuspended: "Owner permission is suspended",
  publicShareResourceUnavailable: "Resource is unavailable",
} as const;

const pl: Record<keyof typeof en, string> = {
  publicShareRateLimited: "Zbyt wiele żądań", publicShareRateLimitedHint: "Odczekaj chwilę i spróbuj ponownie otworzyć ten link.",
  publicShareUnavailable: "Ten link jest niedostępny", publicShareUnavailableHint: "Mógł zostać unieważniony lub zawieszony albo udostępniony element nie jest już dostępny.",
  publicShareLoading: "Wczytywanie udostępnionej zawartości…", publicSharePublicLink: "Link publiczny", publicShareEmptyPlaylist: "Brak dostępnych filmów", publicShareEmptyPlaylistHint: "Ta playlista nie zawiera obecnie filmów, które można pokazać publicznie.", publicSharePlaylist: "Udostępniona playlista", publicShareLoadMore: "Wczytaj więcej", publicShareNotFound: "Nie znaleziono udostępnionego linku",
  profilePermissionPublicSharing: "Udostępnianie publiczne", profilePermissionPublicSharingHint: "Tworzenie i zarządzanie publicznymi linkami do własnych filmów i playlist.",
  publicShareAction: "Link publiczny", publicShareCreate: "Utwórz link publiczny", publicShareDisabledByAdmin: "Udostępnianie publiczne zostało wyłączone przez administratora.", publicShareCopy: "Kopiuj link publiczny", publicShareCopied: "Skopiowano link publiczny", publicShareLocalMedia: "Zezwól na lokalne media", publicShareLocalMediaHint: "Pozwala odtwarzać lokalne media. Włączenie powoduje rotację linku.", publicShareRotate: "Zmień link", publicShareRotateConfirm: "Zmienić ten link? Poprzedni adres natychmiast przestanie działać.", publicShareRevoke: "Unieważnij link", publicShareRevokeConfirm: "Unieważnić ten publiczny link? Tej operacji nie można cofnąć.", publicShareActive: "Aktywny", publicShareSuspended: "Zawieszony", publicShareTokenRotated: "Link publiczny został zmieniony", publicShareError: "Nie udało się zaktualizować linku publicznego.",
  publicSharingSettingsNav: "Udostępnianie", publicSharingTitle: "Udostępnianie publiczne", publicSharingDescription: "Zarządzaj publicznymi linkami tylko do odczytu bez ujawniania profili ani pozostałej części aplikacji.", publicSharingMaster: "Włącz udostępnianie publiczne", publicSharingMasterHint: "Steruje wszystkimi publicznymi linkami w tej instalacji. Po wyłączeniu istniejące linki pozostają zapisane.", publicSharingLinks: "Linki publiczne", publicSharingLinksHint: "Dostęp do lokalnych mediów jest domyślnie wyłączony i ustawiany osobno dla każdego linku.", publicSharingEmpty: "Brak publicznych linków", publicSharingEmptyHint: "Utwórz link na stronie filmu lub playlisty.", publicShareOwner: "Właściciel: {name}", publicShareVideo: "Film", publicShareUserPlaylist: "Osobista playlista", publicShareFollowedPlaylist: "Obserwowana playlista", publicSharePolicyDisabled: "Udostępnianie jest globalnie wyłączone", publicSharePermissionSuspended: "Uprawnienie właściciela jest zawieszone", publicShareResourceUnavailable: "Zasób jest niedostępny",
};

const de: Record<keyof typeof en, string> = {
  publicShareRateLimited: "Zu viele Anfragen", publicShareRateLimitedHint: "Warte kurz und öffne diesen Link erneut.", publicShareUnavailable: "Dieser Freigabelink ist nicht verfügbar", publicShareUnavailableHint: "Er wurde möglicherweise widerrufen oder ausgesetzt, oder das Element ist nicht mehr verfügbar.", publicShareLoading: "Freigegebene Inhalte werden geladen…", publicSharePublicLink: "Öffentlicher Link", publicShareEmptyPlaylist: "Keine verfügbaren Videos", publicShareEmptyPlaylistHint: "Diese Playlist enthält derzeit keine öffentlich sichtbaren Videos.", publicSharePlaylist: "Freigegebene Playlist", publicShareLoadMore: "Mehr laden", publicShareNotFound: "Freigabelink nicht gefunden", profilePermissionPublicSharing: "Öffentliche Freigabe", profilePermissionPublicSharingHint: "Öffentliche Links für eigene Videos und Playlists erstellen und verwalten.", publicShareAction: "Öffentlicher Link", publicShareCreate: "Öffentlichen Link erstellen", publicShareDisabledByAdmin: "Die öffentliche Freigabe wurde administrativ deaktiviert.", publicShareCopy: "Öffentlichen Link kopieren", publicShareCopied: "Öffentlicher Link kopiert", publicShareLocalMedia: "Lokale Medien erlauben", publicShareLocalMediaHint: "Erlaubt die Wiedergabe lokaler Medien. Beim Aktivieren wird der Link rotiert.", publicShareRotate: "Link rotieren", publicShareRotateConfirm: "Diesen Link rotieren? Die vorherige URL funktioniert sofort nicht mehr.", publicShareRevoke: "Link widerrufen", publicShareRevokeConfirm: "Diesen öffentlichen Link widerrufen? Dies kann nicht rückgängig gemacht werden.", publicShareActive: "Aktiv", publicShareSuspended: "Ausgesetzt", publicShareTokenRotated: "Der öffentliche Link wurde rotiert", publicShareError: "Der öffentliche Link konnte nicht aktualisiert werden.", publicSharingSettingsNav: "Freigabe", publicSharingTitle: "Öffentliche Freigabe", publicSharingDescription: "Schreibgeschützte öffentliche Links verwalten, ohne Profile oder die übrige Anwendung offenzulegen.", publicSharingMaster: "Öffentliche Freigabe aktivieren", publicSharingMasterHint: "Steuert alle öffentlichen Links dieser Installation. Vorhandene Links bleiben deaktiviert gespeichert.", publicSharingLinks: "Öffentliche Links", publicSharingLinksHint: "Lokale Medien sind standardmäßig deaktiviert und werden pro Link aktiviert.", publicSharingEmpty: "Keine öffentlichen Links", publicSharingEmptyHint: "Erstelle einen Link auf einer Video- oder Playlistseite.", publicShareOwner: "Eigentümer: {name}", publicShareVideo: "Video", publicShareUserPlaylist: "Persönliche Playlist", publicShareFollowedPlaylist: "Gefolgte Playlist", publicSharePolicyDisabled: "Freigabe ist global deaktiviert", publicSharePermissionSuspended: "Berechtigung des Eigentümers ist ausgesetzt", publicShareResourceUnavailable: "Ressource ist nicht verfügbar",
};

const fr: Record<keyof typeof en, string> = {
  publicShareRateLimited: "Trop de requêtes", publicShareRateLimitedHint: "Patientez un instant puis rouvrez ce lien.", publicShareUnavailable: "Ce lien partagé est indisponible", publicShareUnavailableHint: "Il a peut-être été révoqué ou suspendu, ou l’élément n’est plus disponible.", publicShareLoading: "Chargement du contenu partagé…", publicSharePublicLink: "Lien public", publicShareEmptyPlaylist: "Aucune vidéo disponible", publicShareEmptyPlaylistHint: "Cette playlist ne contient actuellement aucune vidéo affichable publiquement.", publicSharePlaylist: "Playlist partagée", publicShareLoadMore: "Charger plus", publicShareNotFound: "Lien partagé introuvable", profilePermissionPublicSharing: "Partage public", profilePermissionPublicSharingHint: "Créer et gérer des liens publics vers ses propres vidéos et playlists.", publicShareAction: "Lien public", publicShareCreate: "Créer un lien public", publicShareDisabledByAdmin: "Le partage public a été désactivé par un administrateur.", publicShareCopy: "Copier le lien public", publicShareCopied: "Lien public copié", publicShareLocalMedia: "Autoriser les médias locaux", publicShareLocalMediaHint: "Autorise la lecture des médias locaux. L’activation renouvelle le lien.", publicShareRotate: "Renouveler le lien", publicShareRotateConfirm: "Renouveler ce lien ? L’ancienne URL cessera immédiatement de fonctionner.", publicShareRevoke: "Révoquer le lien", publicShareRevokeConfirm: "Révoquer ce lien public ? Cette action est irréversible.", publicShareActive: "Actif", publicShareSuspended: "Suspendu", publicShareTokenRotated: "Le lien public a été renouvelé", publicShareError: "Impossible de mettre à jour le lien public.", publicSharingSettingsNav: "Partage", publicSharingTitle: "Partage public", publicSharingDescription: "Gérez des liens publics en lecture seule sans exposer les profils ni le reste de l’application.", publicSharingMaster: "Activer le partage public", publicSharingMasterHint: "Contrôle tous les liens publics de cette installation. Les liens existants restent enregistrés lorsqu’il est désactivé.", publicSharingLinks: "Liens publics", publicSharingLinksHint: "Les médias locaux sont désactivés par défaut et peuvent être activés pour chaque lien.", publicSharingEmpty: "Aucun lien public", publicSharingEmptyHint: "Créez un lien depuis une page de vidéo ou de playlist.", publicShareOwner: "Propriétaire : {name}", publicShareVideo: "Vidéo", publicShareUserPlaylist: "Playlist personnelle", publicShareFollowedPlaylist: "Playlist suivie", publicSharePolicyDisabled: "Le partage est désactivé globalement", publicSharePermissionSuspended: "L’autorisation du propriétaire est suspendue", publicShareResourceUnavailable: "La ressource est indisponible",
};

const es: Record<keyof typeof en, string> = {
  publicShareRateLimited: "Demasiadas solicitudes", publicShareRateLimitedHint: "Espera un momento e intenta abrir de nuevo este enlace.", publicShareUnavailable: "Este enlace compartido no está disponible", publicShareUnavailableHint: "Puede haberse revocado o suspendido, o el elemento ya no está disponible.", publicShareLoading: "Cargando contenido compartido…", publicSharePublicLink: "Enlace público", publicShareEmptyPlaylist: "No hay vídeos disponibles", publicShareEmptyPlaylistHint: "Esta lista no contiene actualmente vídeos que puedan mostrarse públicamente.", publicSharePlaylist: "Lista compartida", publicShareLoadMore: "Cargar más", publicShareNotFound: "No se encontró el enlace compartido", profilePermissionPublicSharing: "Uso compartido público", profilePermissionPublicSharingHint: "Crear y gestionar enlaces públicos a vídeos y listas propios.", publicShareAction: "Enlace público", publicShareCreate: "Crear enlace público", publicShareDisabledByAdmin: "Un administrador ha desactivado el uso compartido público.", publicShareCopy: "Copiar enlace público", publicShareCopied: "Enlace público copiado", publicShareLocalMedia: "Permitir medios locales", publicShareLocalMediaHint: "Permite reproducir medios locales. Al activarlo se renueva el enlace.", publicShareRotate: "Renovar enlace", publicShareRotateConfirm: "¿Renovar este enlace? La URL anterior dejará de funcionar inmediatamente.", publicShareRevoke: "Revocar enlace", publicShareRevokeConfirm: "¿Revocar este enlace público? Esta acción no se puede deshacer.", publicShareActive: "Activo", publicShareSuspended: "Suspendido", publicShareTokenRotated: "El enlace público se ha renovado", publicShareError: "No se pudo actualizar el enlace público.", publicSharingSettingsNav: "Compartir", publicSharingTitle: "Uso compartido público", publicSharingDescription: "Gestiona enlaces públicos de solo lectura sin exponer perfiles ni el resto de la aplicación.", publicSharingMaster: "Activar uso compartido público", publicSharingMasterHint: "Controla todos los enlaces públicos de esta instalación. Los existentes permanecen guardados al desactivarlo.", publicSharingLinks: "Enlaces públicos", publicSharingLinksHint: "Los medios locales están desactivados de forma predeterminada y se habilitan por enlace.", publicSharingEmpty: "No hay enlaces públicos", publicSharingEmptyHint: "Crea un enlace desde una página de vídeo o lista.", publicShareOwner: "Propietario: {name}", publicShareVideo: "Vídeo", publicShareUserPlaylist: "Lista personal", publicShareFollowedPlaylist: "Lista seguida", publicSharePolicyDisabled: "El uso compartido está desactivado globalmente", publicSharePermissionSuspended: "El permiso del propietario está suspendido", publicShareResourceUnavailable: "El recurso no está disponible",
};

const ptBR: Record<keyof typeof en, string> = {
  publicShareRateLimited: "Muitas solicitações", publicShareRateLimitedHint: "Aguarde um momento e tente abrir este link novamente.", publicShareUnavailable: "Este link compartilhado não está disponível", publicShareUnavailableHint: "Ele pode ter sido revogado ou suspenso, ou o item não está mais disponível.", publicShareLoading: "Carregando conteúdo compartilhado…", publicSharePublicLink: "Link público", publicShareEmptyPlaylist: "Nenhum vídeo disponível", publicShareEmptyPlaylistHint: "Esta playlist não contém vídeos que possam ser exibidos publicamente no momento.", publicSharePlaylist: "Playlist compartilhada", publicShareLoadMore: "Carregar mais", publicShareNotFound: "Link compartilhado não encontrado", profilePermissionPublicSharing: "Compartilhamento público", profilePermissionPublicSharingHint: "Criar e gerenciar links públicos para vídeos e playlists próprios.", publicShareAction: "Link público", publicShareCreate: "Criar link público", publicShareDisabledByAdmin: "O compartilhamento público foi desativado por um administrador.", publicShareCopy: "Copiar link público", publicShareCopied: "Link público copiado", publicShareLocalMedia: "Permitir mídia local", publicShareLocalMediaHint: "Permite reproduzir mídia local. Ativar renova o link.", publicShareRotate: "Renovar link", publicShareRotateConfirm: "Renovar este link? A URL anterior deixará de funcionar imediatamente.", publicShareRevoke: "Revogar link", publicShareRevokeConfirm: "Revogar este link público? Isso não pode ser desfeito.", publicShareActive: "Ativo", publicShareSuspended: "Suspenso", publicShareTokenRotated: "O link público foi renovado", publicShareError: "Não foi possível atualizar o link público.", publicSharingSettingsNav: "Compartilhamento", publicSharingTitle: "Compartilhamento público", publicSharingDescription: "Gerencie links públicos somente leitura sem expor perfis ou o restante do aplicativo.", publicSharingMaster: "Ativar compartilhamento público", publicSharingMasterHint: "Controla todos os links públicos desta instalação. Os links existentes permanecem armazenados quando desativado.", publicSharingLinks: "Links públicos", publicSharingLinksHint: "A mídia local fica desativada por padrão e pode ser ativada por link.", publicSharingEmpty: "Nenhum link público", publicSharingEmptyHint: "Crie um link em uma página de vídeo ou playlist.", publicShareOwner: "Proprietário: {name}", publicShareVideo: "Vídeo", publicShareUserPlaylist: "Playlist pessoal", publicShareFollowedPlaylist: "Playlist seguida", publicSharePolicyDisabled: "O compartilhamento está desativado globalmente", publicSharePermissionSuspended: "A permissão do proprietário está suspensa", publicShareResourceUnavailable: "O recurso não está disponível",
};

const ru: Record<keyof typeof en, string> = {
  publicShareRateLimited: "Слишком много запросов", publicShareRateLimitedHint: "Подождите немного и снова откройте эту ссылку.", publicShareUnavailable: "Эта общая ссылка недоступна", publicShareUnavailableHint: "Возможно, она отозвана или приостановлена либо материал больше недоступен.", publicShareLoading: "Загрузка общего содержимого…", publicSharePublicLink: "Публичная ссылка", publicShareEmptyPlaylist: "Нет доступных видео", publicShareEmptyPlaylistHint: "Сейчас в этом плейлисте нет видео для публичного показа.", publicSharePlaylist: "Общий плейлист", publicShareLoadMore: "Загрузить ещё", publicShareNotFound: "Общая ссылка не найдена", profilePermissionPublicSharing: "Публичный доступ", profilePermissionPublicSharingHint: "Создание и управление публичными ссылками на собственные видео и плейлисты.", publicShareAction: "Публичная ссылка", publicShareCreate: "Создать публичную ссылку", publicShareDisabledByAdmin: "Публичный доступ отключён администратором.", publicShareCopy: "Копировать публичную ссылку", publicShareCopied: "Публичная ссылка скопирована", publicShareLocalMedia: "Разрешить локальные медиа", publicShareLocalMediaHint: "Разрешает воспроизведение локальных медиа. Включение обновляет ссылку.", publicShareRotate: "Обновить ссылку", publicShareRotateConfirm: "Обновить ссылку? Предыдущий URL сразу перестанет работать.", publicShareRevoke: "Отозвать ссылку", publicShareRevokeConfirm: "Отозвать публичную ссылку? Это действие нельзя отменить.", publicShareActive: "Активна", publicShareSuspended: "Приостановлена", publicShareTokenRotated: "Публичная ссылка обновлена", publicShareError: "Не удалось обновить публичную ссылку.", publicSharingSettingsNav: "Общий доступ", publicSharingTitle: "Публичный доступ", publicSharingDescription: "Управляйте публичными ссылками только для чтения, не раскрывая профили и остальную часть приложения.", publicSharingMaster: "Включить публичный доступ", publicSharingMasterHint: "Управляет всеми публичными ссылками этой установки. При отключении существующие ссылки сохраняются.", publicSharingLinks: "Публичные ссылки", publicSharingLinksHint: "Локальные медиа по умолчанию отключены и включаются отдельно для каждой ссылки.", publicSharingEmpty: "Нет публичных ссылок", publicSharingEmptyHint: "Создайте ссылку на странице видео или плейлиста.", publicShareOwner: "Владелец: {name}", publicShareVideo: "Видео", publicShareUserPlaylist: "Личный плейлист", publicShareFollowedPlaylist: "Отслеживаемый плейлист", publicSharePolicyDisabled: "Общий доступ глобально отключён", publicSharePermissionSuspended: "Разрешение владельца приостановлено", publicShareResourceUnavailable: "Ресурс недоступен",
};

const ja: Record<keyof typeof en, string> = {
  publicShareRateLimited: "リクエストが多すぎます", publicShareRateLimitedHint: "少し待ってから、この共有リンクをもう一度開いてください。", publicShareUnavailable: "この共有リンクは利用できません", publicShareUnavailableHint: "取り消しまたは停止されたか、共有項目が利用できなくなった可能性があります。", publicShareLoading: "共有コンテンツを読み込んでいます…", publicSharePublicLink: "公開リンク", publicShareEmptyPlaylist: "利用できる動画がありません", publicShareEmptyPlaylistHint: "現在、この再生リストには公開できる動画がありません。", publicSharePlaylist: "共有再生リスト", publicShareLoadMore: "さらに読み込む", publicShareNotFound: "共有リンクが見つかりません", profilePermissionPublicSharing: "公開共有", profilePermissionPublicSharingHint: "所有する動画と再生リストへの公開リンクを作成、管理します。", publicShareAction: "公開リンク", publicShareCreate: "公開リンクを作成", publicShareDisabledByAdmin: "公開共有は管理者によって無効にされています。", publicShareCopy: "公開リンクをコピー", publicShareCopied: "公開リンクをコピーしました", publicShareLocalMedia: "ローカルメディアを許可", publicShareLocalMediaHint: "ローカルメディアを再生できます。有効化するとリンクが更新されます。", publicShareRotate: "リンクを更新", publicShareRotateConfirm: "このリンクを更新しますか？以前のURLは直ちに無効になります。", publicShareRevoke: "リンクを取り消す", publicShareRevokeConfirm: "この公開リンクを取り消しますか？この操作は元に戻せません。", publicShareActive: "有効", publicShareSuspended: "停止中", publicShareTokenRotated: "公開リンクを更新しました", publicShareError: "公開リンクを更新できませんでした。", publicSharingSettingsNav: "共有", publicSharingTitle: "公開共有", publicSharingDescription: "プロフィールやアプリの他の部分を公開せずに、読み取り専用の公開リンクを管理します。", publicSharingMaster: "公開共有を有効にする", publicSharingMasterHint: "このインストールのすべての公開リンクを制御します。無効にしても既存リンクは保存されます。", publicSharingLinks: "公開リンク", publicSharingLinksHint: "ローカルメディアは既定で無効で、リンクごとに有効化できます。", publicSharingEmpty: "公開リンクはありません", publicSharingEmptyHint: "動画または再生リストのページからリンクを作成してください。", publicShareOwner: "所有者: {name}", publicShareVideo: "動画", publicShareUserPlaylist: "個人再生リスト", publicShareFollowedPlaylist: "フォロー中の再生リスト", publicSharePolicyDisabled: "共有は全体で無効です", publicSharePermissionSuspended: "所有者の権限が停止されています", publicShareResourceUnavailable: "リソースを利用できません",
};

const hu: Record<keyof typeof en, string> = {
  publicShareRateLimited: "Túl sok kérés", publicShareRateLimitedHint: "Várj egy kicsit, majd nyisd meg újra ezt a hivatkozást.", publicShareUnavailable: "Ez a megosztott hivatkozás nem érhető el", publicShareUnavailableHint: "Lehet, hogy visszavonták vagy felfüggesztették, illetve az elem már nem érhető el.", publicShareLoading: "Megosztott tartalom betöltése…", publicSharePublicLink: "Nyilvános hivatkozás", publicShareEmptyPlaylist: "Nincs elérhető videó", publicShareEmptyPlaylistHint: "A lejátszási listán jelenleg nincs nyilvánosan megjeleníthető videó.", publicSharePlaylist: "Megosztott lejátszási lista", publicShareLoadMore: "Továbbiak betöltése", publicShareNotFound: "A megosztott hivatkozás nem található", profilePermissionPublicSharing: "Nyilvános megosztás", profilePermissionPublicSharingHint: "Nyilvános hivatkozások létrehozása és kezelése saját videókhoz és lejátszási listákhoz.", publicShareAction: "Nyilvános hivatkozás", publicShareCreate: "Nyilvános hivatkozás létrehozása", publicShareDisabledByAdmin: "A nyilvános megosztást egy rendszergazda kikapcsolta.", publicShareCopy: "Nyilvános hivatkozás másolása", publicShareCopied: "Nyilvános hivatkozás másolva", publicShareLocalMedia: "Helyi média engedélyezése", publicShareLocalMediaHint: "Engedélyezi a helyi média lejátszását. Bekapcsoláskor a hivatkozás megújul.", publicShareRotate: "Hivatkozás megújítása", publicShareRotateConfirm: "Megújítod ezt a hivatkozást? A korábbi URL azonnal megszűnik.", publicShareRevoke: "Hivatkozás visszavonása", publicShareRevokeConfirm: "Visszavonod ezt a nyilvános hivatkozást? Ez nem vonható vissza.", publicShareActive: "Aktív", publicShareSuspended: "Felfüggesztve", publicShareTokenRotated: "A nyilvános hivatkozás megújult", publicShareError: "A nyilvános hivatkozás nem frissíthető.", publicSharingSettingsNav: "Megosztás", publicSharingTitle: "Nyilvános megosztás", publicSharingDescription: "Írásvédett nyilvános hivatkozások kezelése a profilok és az alkalmazás többi részének felfedése nélkül.", publicSharingMaster: "Nyilvános megosztás engedélyezése", publicSharingMasterHint: "A telepítés összes nyilvános hivatkozását vezérli. Kikapcsoláskor a meglévő hivatkozások megmaradnak.", publicSharingLinks: "Nyilvános hivatkozások", publicSharingLinksHint: "A helyi média alapértelmezetten ki van kapcsolva, és hivatkozásonként engedélyezhető.", publicSharingEmpty: "Nincs nyilvános hivatkozás", publicSharingEmptyHint: "Hozz létre hivatkozást egy videó vagy lejátszási lista oldaláról.", publicShareOwner: "Tulajdonos: {name}", publicShareVideo: "Videó", publicShareUserPlaylist: "Személyes lejátszási lista", publicShareFollowedPlaylist: "Követett lejátszási lista", publicSharePolicyDisabled: "A megosztás globálisan ki van kapcsolva", publicSharePermissionSuspended: "A tulajdonos jogosultsága fel van függesztve", publicShareResourceUnavailable: "Az erőforrás nem érhető el",
};

export const publicSharingMessages = { en, pl, de, fr, es, "pt-BR": ptBR, ru, ja, hu } as const;
