import { describe, expect, test } from "bun:test";
import { sqliteCreateIndexToPostgres, sqliteCreateTableToPostgres } from "./postgresMigration";

describe("SQLite to PostgreSQL schema translation", () => {
  test("translates identity, timestamps, blobs and real numbers", () => {
    const result = sqliteCreateTableToPostgres(`CREATE TABLE IF NOT EXISTS events (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      score REAL,
      payload BLOB,
      local_day TEXT DEFAULT (date('now', 'localtime')),
      local_hour INTEGER DEFAULT (CAST(strftime('%H', 'now', 'localtime') AS INTEGER)),
      created_at TEXT NOT NULL DEFAULT (datetime('now'))
    )`);
    expect(result).toContain("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
    expect(result).toContain("DOUBLE PRECISION");
    expect(result).toContain("BYTEA");
    expect(result).toContain("DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");
    expect(result).toContain("DEFAULT (CURRENT_DATE::text)");
    expect(result).toContain("EXTRACT(HOUR FROM LOCALTIME)");
    expect(result).not.toContain("REFERENCES");
    expect(result).not.toContain("AUTOINCREMENT");
  });

  test("removes SQLite-only collation and IF NOT EXISTS", () => {
    expect(sqliteCreateTableToPostgres("CREATE TABLE IF NOT EXISTS tags (name TEXT COLLATE NOCASE)")).toBe("CREATE TABLE tags (name TEXT)");
    expect(sqliteCreateIndexToPostgres("CREATE UNIQUE INDEX IF NOT EXISTS idx_tags ON tags(name COLLATE NOCASE)")).toBe("CREATE UNIQUE INDEX idx_tags ON tags(name)");
  });
});
